"""GrandPrix Watcher package."""

from grandprix_watcher.core import (
    AppConfig,
    LinkItem,
    NotifyConfig,
    WatchConfig,
    as_string_list,
    build_config,
    check_once,
    crawl_links,
    event_regex,
    extract_links,
    item_matches,
    load_config,
    load_seen,
    normalize_grand_prix,
    normalize_search_text,
    normalize_text,
    notify,
    save_seen,
)

__all__ = [
    "AppConfig",
    "LinkItem",
    "NotifyConfig",
    "WatchConfig",
    "as_string_list",
    "build_config",
    "check_once",
    "crawl_links",
    "event_regex",
    "extract_links",
    "item_matches",
    "load_config",
    "load_seen",
    "normalize_grand_prix",
    "normalize_search_text",
    "normalize_text",
    "notify",
    "save_seen",
]
